[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minase-driver = { path = "../driver"}
minase = { path = "../minase"}
tokio = { version = "1.33.0", features = ["full"] }


